In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(pd.read_csv('SuperMarket - SuperMarket.csv'))

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   str
 1   Branch                   1014 non-null   str
 2   City                     1014 non-null   str
 3   Customer type            1014 non-null   str
 4   Gender                   1014 non-null   str
 5   Product line             1014 non-null   str
 6   Unit price               990 non-null    float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    994 non-null    str
 10  Date                     1002 non-null   str
 11  Time                     1014 non-null   str
 12  Payment                  1014 non-null   str
 13  cogs                     1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(6), int64(1), str(10)
memory usage: 134.8 KB

In [6]:
df.describe()

,Unit price,Quantity,Tax 5%,cogs,gross margin percentage,gross income,Rating
count,990.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000
mean,55.520333,5.502959,15.337247,306.737436,4.761905,15.337247,6.960454
std,26.330508,2.927133,11.685745,233.718896,0.000000,11.685745,1.721264
min,10.080000,1.000000,0.508500,10.170000,4.761905,0.508500,4.000000
25%,33.202500,3.000000,5.864625,117.292500,4.761905,5.864625,5.500000
50%,54.890000,5.000000,12.066000,241.320000,4.761905,12.066000,6.900000
75%,77.667500,8.000000,22.428000,448.560000,4.761905,22.428000,8.475000
max,99.960000,10.000000,49.650000,993.000000,4.761905,49.650000,10.000000

In [7]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='str')

In [8]:
df.dtypes

Invoice ID                     str
Branch                         str
City                           str
Customer type                  str
Gender                         str
Product line                   str
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                          str
Date                           str
Time                           str
Payment                        str
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [9]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.22,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.048,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaN,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3

In [10]:
df.shape

(1014, 17)

In [11]:
df.isna().sum()

Invoice ID                  0
Branch                      0
City                        0
Customer type               0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
cogs                        0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [12]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1009     True
1010     True
1011     True
1012     True
1013     True
Length: 1014, dtype: bool

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [16]:
print(df['Date'].dtype)

datetime64[us]

In [17]:
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')

In [18]:
print(df['Sales'].dtype)

float64

In [19]:
sales_null=((df['Unit price']*df['Quantity'])+df['Tax 5%'])

In [20]:
df.fillna({'Sales':sales_null},inplace=True)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaT,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [21]:
df['Sales'].isna().sum()

np.int64(0)

In [22]:
df.isna().sum()

Invoice ID                  0
Branch                      0
City                        0
Customer type               0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                       0
Date                       12
Time                        0
Payment                     0
cogs                        0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [23]:
UnitPrice_null= (df['Sales']-df['Tax 5%'])/df['Quantity']

In [24]:
df.fillna({'Unit price':UnitPrice_null},inplace=True)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaT,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [25]:
df['Unit price'].isna().sum()

np.int64(0)

In [26]:
df['Year']=df['Date'].dt.year

In [27]:
df['Month']=df['Date'].dt.month

In [28]:
df['Day']=df['Date'].dt.day

In [29]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Year,Month,Day
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,2019.0,1.0,5.0
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6,2019.0,3.0,8.0
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4,2019.0,3.0,3.0
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,2019.0,1.0,27.0
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaT,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3,NaN,NaN,NaN

In [30]:
df['Branch']=df['Branch'].str.replace("giza","Giza")
df['Branch']=df['Branch'].str.replace("cairo","Cairo")

In [31]:
df['Satisfaction'] = df['Rating'].apply(lambda Rating: 'Satisfied' if Rating>=7 else 'Not Satisfied' )

In [32]:
df['Satisfaction']

0          Satisfied
1          Satisfied
2          Satisfied
3          Satisfied
4      Not Satisfied
           ...
995    Not Satisfied
996    Not Satisfied
997        Satisfied
998    Not Satisfied
999    Not Satisfied
Name: Satisfaction, Length: 1000, dtype: str

In [33]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,...,Time,Payment,cogs,gross margin percentage,gross income,Rating,Year,Month,Day,Satisfaction
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,...,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,2019.0,1.0,5.0,Satisfied
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,...,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6,2019.0,3.0,8.0,Satisfied
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,...,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4,2019.0,3.0,3.0,Satisfied
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,...,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,2019.0,1.0,27.0,Satisfied
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,...,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3,NaN,NaN,NaN,Not Satisfied

In [34]:
df.to_csv('SuperMarket_CleanedData')

## Data Analysis

In [35]:
data = pd.DataFrame(pd.read_csv('SuperMarket_CleanedData'))

In [56]:
data.columns

Index(['Unnamed: 0', 'Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating', 'Year', 'Month', 'Day', 'Satisfaction'],
      dtype='str')

In [60]:
Total_Revenue = data['Sales'].sum().round(2)
print(f'TotalRevenue is : {Total_Revenue}')

TotalRevenue is : 322966.75

In [59]:
print(f'TotalRevenue is : {Total_Revenue}')

TotalRevenue is : 322966.75

In [67]:
Cities_Revenue = data.groupby('City')['Sales'].sum().round(2).sort_values(ascending=False).reset_index()
Cities_Revenue

        City      Sales
0  Naypyitaw  110568.71
1     Yangon  106200.37
2   Mandalay  106197.67

In [66]:
print(f' the city with the highest revenue is : {Cities_Revenue.iloc[0,0]}')

 the city with the highest revenue is : Naypyitaw

In [68]:
Branches_Profit = data.groupby('Branch')['gross income'].sum().round(2).sort_values(ascending=False).reset_index()
Branches_Profit

  Branch  gross income
0   Giza       5265.18
1   Alex       5057.35
2  Cairo       5057.22

In [69]:
print(f' the Branch with the highest Profit is : {Branches_Profit.iloc[0,0]}')

 the Branch with the highest Profit is : Giza

In [42]:
Category_Performance = data.groupby('Product line')[['Sales','gross income']].sum().round(2).sort_values(['Sales','gross income'],ascending=[False,False]).reset_index()
Category_Performance

             Product line     Sales  gross income
0      Food and beverages  56144.84       2673.75
1       Sports and travel  55122.83       2624.90
2  Electronic accessories  54337.53       2587.50
3     Fashion accessories  54305.90       2586.18
4      Home and lifestyle  53861.91       2564.85
5       Health and beauty  49193.74       2342.56

In [43]:
print(f'the top-performing category is : {Category_Performance.iloc[0,0]}')

the top-performing category is : Food and beverages

In [44]:
Customers_Style = data.groupby('Customer type')['Sales'].sum().sort_values(ascending=False).reset_index()
Customers_Style

  Customer type       Sales
0        Member  189694.764
1        Normal  133271.985

In [45]:
print(f'the customer type spends more is : {Customers_Style.iloc[0,0]}')

the customer type spends more is : Member

In [46]:
Payment_Methods = data.groupby('Payment')['Invoice ID'].count().sort_values(ascending=False).reset_index()
Payment_Methods

       Payment  Invoice ID
0      Ewallet         341
1         Cash         337
2  Credit card         306
3         cash           7
4  credit card           5
5     E-wallet           4

In [47]:
print(f'the most popular payment method is : {Payment_Methods.iloc[0,0]}')

the most popular payment method is : Ewallet

In [70]:
Average_Transaction = data['Sales'].sum().mean()

In [71]:
print(f'the average transaction value for the supermarket is : {Average_Transaction}')

the average transaction value for the supermarket is : 322966.749

In [50]:
Customer_Satisfaction = data.groupby('Branch')['Satisfaction'].value_counts(normalize=True).mul(100).round(2).sort_values(ascending=False).reset_index(name='Percentage')
Customer_Satisfaction

  Branch   Satisfaction  Percentage
0  Cairo  Not Satisfied       54.52
1   Alex      Satisfied       52.65
2   Giza      Satisfied       52.13
3   Giza  Not Satisfied       47.87
4   Alex  Not Satisfied       47.35
5  Cairo      Satisfied       45.48

In [52]:
highest_Satisfaction =Customer_Satisfaction[Customer_Satisfaction['Satisfaction'] == 'Satisfied'].sort_values('Percentage',ascending=False)
highest_Satisfaction

  Branch Satisfaction  Percentage
1   Alex    Satisfied       52.65
2   Giza    Satisfied       52.13
5  Cairo    Satisfied       45.48

In [53]:
print(f'The highest_Satisfaction Branch is : {highest_Satisfaction.iloc[0,0]} with a {highest_Satisfaction.iloc[0]['Percentage']} % Percentage')

The highest_Satisfaction Branch is : Alex with a 52.65 % Percentage

In [54]:
Revenue_trend = data.groupby(['Year','Day','Month'])['Sales'].sum().round(2).sort_values(ascending=False).reset_index()
Revenue_trend

      Year   Day  Month    Sales
0   2019.0   9.0    3.0  7366.91
1   2019.0  14.0    3.0  7214.63
2   2019.0  15.0    2.0  6830.79
3   2019.0   7.0    2.0  6774.72
4   2019.0   2.0    3.0  6560.31
..     ...   ...    ...      ...
84  2019.0  18.0    2.0  1496.03
85  2019.0   7.0    3.0  1438.26
86  2019.0  21.0    2.0  1393.74
87  2019.0  18.0    3.0  1292.83
88  2019.0  13.0    2.0   934.24

[89 rows x 4 columns]

In [55]:
print(f'The highest Sales was in :\n{Revenue_trend.iloc[0,0:3]}')

The highest Sales was in :
Year     2019.0
Day         9.0
Month       3.0
Name: 0, dtype: float64